### ISSUE TITLE
Faild: XXX may not be empty

### ISSUE THREAD

**Issue by pavelloz** [sinofseven/serverless-s3-remover#12]
Im trying to remove S3 buckets created by serverless but i get:
```
S3 Remover: Faild: us-east-1-input-dev may not be empty.
S3 Remover: Faild: us-east-1-output-dev may not be empty.
```

It looks like im not the only one:
https://github.com/serverless/serverless/issues/3679#issuecomment-374036184 

To be honest, when i go to bucket list in AWS console i cant see any of those buckets, so i dont know if the message (apart from typo in `Failed` ;) ) is misleading or serverless is creating those buckets in some other way thats impossible to see them (im looking here https://s3.console.aws.amazon.com/s3/home?region=us-east-1 ) 

![image](https://user-images.githubusercontent.com/546845/44268470-de365500-a231-11e8-9e92-712024e2def5.png)

**Comment by sinofseven** [comment]
@pavelloz 

This message is displayed in the following two cases.
- Failed to acquire object list of bucket
- Failed to delete the object

At this time, it was supposed that the object remained in the bucket, so we were putting the message "Faild: XXX may not be empty".
Is it better to express that the deletion of the object failed?

**Comment by pavelloz** [comment]
Hey,

In my case im pretty sure its the second case if those two are the only options (S3 bucket doesn't exist at all), so IMO there should be 2 different messages for those two cases, because "may not be empty" suggests that it does exist and it tried to delete it, but didnt for some reason.

I dont know if there is a way to differentiate them using any check, so maybe just changing message to what you wrote above would be the best possible way of informing about it :)

**Comment by ghost** [comment]
Thank you, your suggestion.
I will try out how to do something.

**Comment by pavelloz** [comment]
Thank you :)
