### ISSUE TITLE
Add to serverless plugins page

### ISSUE THREAD

**Issue by ryanmurakami** [sinofseven/serverless-s3-remover#2]
Awesome plugin! I was just looking for something like this. 

It would be great to have this on the [Serverless plugins page](https://github.com/serverless/plugins) so it would be easy to find.

**Comment by horike37** [comment]
I agree with @ryanmurakami !
Many people will know your plugin if you post it on this page.
I recommend you to send PR.

**Comment by sinofseven** [comment]
Thank you very much.  
I will send PR.

**Comment by sinofseven** [comment]
The PR sended by me was merged.
Thank you very much!
